ServerName          "My FTP Server"
ServerType          standalone
DefaultServer       on
Port                21
Umask               000
SystemLog           /var/log/proftpd/proftpd.log
TransferLog         /var/log/proftpd/xferlog
WtmpLog             off
ScoreboardFile      /var/run/proftpd.score

# Schimbați 'change_me' cu numele unui utilizator valid din sistem
User                change_me
Group               appsusers
RequireValidShell   off
DefaultRoot         /Storage

# Directory specific settings
<Directory /Storage/*>
  AllowOverwrite    on
  <Limit ALL>
    AllowUser       change_me
    DenyAll
  </Limit>
</Directory>

MaxInstances        30
